$:
  vscode:
    - docker:
        image: docker.cnb.cool/anyexyz/ollama/env/dockerfile-caches
      runner:
        cpus: 16
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &