$:
  vscode:
    - docker:
        image: docker.cnb.cool/opencamp/learning-ai/ai-course-lab-basic:latest
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &

main:
  push:
    - services:
        - docker
      runner:
        tags: cnb:arch:amd64
      stages:
        - name: 构建 Docker 镜像
          script: |
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest -f .ide/Dockerfile .
        - name: 推送 Docker 镜像
          script: |
            docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
    
    - docker:
        image: docker.cnb.cool/opencamp/learning-ai/ai-course-lab-basic:latest
      runner:
        tags: cnb:arch:amd64
        cpus: 16
      volumes:
        - models:copy-on-write
        - /root/.cache/pip:copy-on-write
      stages:
        - name: 启动 Ollama
          script: |
            nohup ollama serve > /tmp/ollama.log 2>&1 &
            sleep 5
            for i in {1..30}; do
              if curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
                echo "Ollama 已就绪"
                break
              fi
              sleep 2
            done
        - name: 安装依赖并测试
          script: |
            cd ai-course-labs
            pip3 install -r requirements.txt
            pytest grader/ -v --json-report --json-report-file=report.json
        - name: 测试报告
          script: |
            cd ai-course-labs
            if [ -f report.json ]; then
              echo "测试完成"
              cat report.json | grep -o '"passed":[0-9]*' || true
              cat report.json | grep -o '"failed":[0-9]*' || true
            else
              echo "未找到报告文件"
            fi

  pull_request:
    - docker:
        image: docker.cnb.cool/opencamp/learning-ai/ai-course-lab-basic:latest
      runner:
        tags: cnb:arch:amd64
        cpus: 16
      volumes:
        - models:copy-on-write
        - /root/.cache/pip:copy-on-write
      stages:
        - name: 启动 Ollama
          script: |
            nohup ollama serve > /tmp/ollama.log 2>&1 &
            sleep 5
            for i in {1..30}; do
              if curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
                echo "Ollama 已就绪"
                break
              fi
              sleep 2
            done
        - name: 安装依赖并测试
          script: |
            cd ai-course-labs
            pip3 install -r requirements.txt
            pytest grader/ -v --json-report --json-report-file=report.json
        - name: 测试报告
          script: |
            cd ai-course-labs
            if [ -f report.json ]; then
              echo "测试完成"
              cat report.json | grep -o '"passed":[0-9]*' || true
              cat report.json | grep -o '"failed":[0-9]*' || true
            else
              echo "未找到报告文件"
            fi